name: benchmark_harness
version: 1.0.4
author: Dart Project <johnmccutchan@google.com>
description: The official Dart project benchmark harness.
homepage: http://www.dartlang.org
dependencies:
  browser: ">=0.10.0+2 <0.11.0"
dev_dependencies:
  unittest: ">=0.10.0 <0.11.0"
  hop: ">=0.30.3 <0.31.0"
  path: ">=1.1.0 <2.0.0"
